// <auto-generated />
using System;
using EKvarovi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EKvarovi.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EKvarovi.Api.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("FaultReportId")
                        .HasColumnType("integer")
                        .HasColumnName("fault_report_id");

                    b.Property<int?>("InterventionId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<short>("Purpose")
                        .HasColumnType("smallint")
                        .HasColumnName("purpose");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("relative_path");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stored_file_name");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("FaultReportId")
                        .HasDatabaseName("ix_attachments_fault_report_id");

                    b.HasIndex("InterventionId")
                        .HasDatabaseName("ix_attachments_intervention_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_attachments_uploaded_by_user_id");

                    b.ToTable("attachments", null, t =>
                        {
                            t.HasCheckConstraint("ck_attachments_purpose_range", "purpose BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_attachments_purpose_target", "(purpose IN (1, 3) AND fault_report_id IS NOT NULL AND intervention_id IS NULL)\r\nOR\r\n(purpose = 2 AND intervention_id IS NOT NULL AND fault_report_id IS NULL)");
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.FaultReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int?>("ClosedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("closed_by_user_id");

                    b.Property<string>("ClosingNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("closing_note");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<int?>("FaultPriorityId")
                        .HasColumnType("integer")
                        .HasColumnName("fault_priority_id");

                    b.Property<int>("FaultStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("fault_status_id");

                    b.Property<int?>("FaultTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("fault_type_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("ReportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("report_number");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reported_by_user_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_fault_reports");

                    b.HasIndex("ClosedByUserId")
                        .HasDatabaseName("ix_fault_reports_closed_by_user_id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ix_fault_reports_due_date");

                    b.HasIndex("FaultPriorityId")
                        .HasDatabaseName("ix_fault_reports_fault_priority_id");

                    b.HasIndex("FaultStatusId")
                        .HasDatabaseName("ix_fault_reports_fault_status_id");

                    b.HasIndex("FaultTypeId")
                        .HasDatabaseName("ix_fault_reports_fault_type_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_fault_reports_location_id");

                    b.HasIndex("ReportNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_fault_reports_report_number");

                    b.HasIndex("ReportedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_fault_reports_reported_at");

                    b.HasIndex("ReportedByUserId")
                        .HasDatabaseName("ix_fault_reports_reported_by_user_id");

                    b.HasIndex("ReviewedByUserId")
                        .HasDatabaseName("ix_fault_reports_reviewed_by_user_id");

                    b.ToTable("fault_reports", (string)null);
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.FaultReportHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("ChangeType")
                        .HasColumnType("smallint")
                        .HasColumnName("change_type");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_user_id");

                    b.Property<int>("FaultReportId")
                        .HasColumnType("integer")
                        .HasColumnName("fault_report_id");

                    b.Property<string>("NewValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("new_value");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("OldValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("old_value");

                    b.HasKey("Id")
                        .HasName("pk_fault_report_histories");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("ix_fault_report_histories_changed_by_user_id");

                    b.HasIndex("FaultReportId", "ChangedAt")
                        .HasDatabaseName("ix_histories_report_changed");

                    b.ToTable("fault_report_histories", (string)null);
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Intervention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("FaultReportId")
                        .HasColumnType("integer")
                        .HasColumnName("fault_report_id");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("InterventionStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_status_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("TechnicianUserId")
                        .HasColumnType("integer")
                        .HasColumnName("technician_user_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.Property<int>("WorkAssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("work_assignment_id");

                    b.HasKey("Id")
                        .HasName("pk_interventions");

                    b.HasIndex("FaultReportId")
                        .HasDatabaseName("ix_interventions_fault_report_id");

                    b.HasIndex("InterventionStatusId")
                        .HasDatabaseName("ix_interventions_intervention_status_id");

                    b.HasIndex("StartedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_interventions_started_at");

                    b.HasIndex("TechnicianUserId")
                        .HasDatabaseName("ix_interventions_technician_user_id");

                    b.HasIndex("WorkAssignmentId")
                        .HasDatabaseName("ix_interventions_work_assignment_id");

                    b.ToTable("interventions", null, t =>
                        {
                            t.HasCheckConstraint("ck_interventions_times", "finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at");
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.InterventionMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("InterventionId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_id");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPriceSnapshot")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_intervention_materials");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_intervention_materials_material_id");

                    b.HasIndex("InterventionId", "MaterialId")
                        .IsUnique()
                        .HasDatabaseName("ux_intervention_materials_unique_item");

                    b.ToTable("intervention_materials", null, t =>
                        {
                            t.HasCheckConstraint("ck_intervention_materials_quantity", "quantity > 0 AND quantity <= 99999.99");
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("location_type_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("postal_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_locations_code");

                    b.HasIndex("LocationTypeId")
                        .HasDatabaseName("ix_locations_location_type_id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Lookups.FaultPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color_hex");

                    b.Property<int>("DefaultResolutionHours")
                        .HasColumnType("integer")
                        .HasColumnName("default_resolution_hours");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_fault_priorities");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_fault_priorities_name");

                    b.ToTable("fault_priorities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#6c757d",
                            DefaultResolutionHours = 168,
                            IsActive = true,
                            Name = "Nizak",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#0d6efd",
                            DefaultResolutionHours = 72,
                            IsActive = true,
                            Name = "Srednji",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#fd7e14",
                            DefaultResolutionHours = 24,
                            IsActive = true,
                            Name = "Visok",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#dc3545",
                            DefaultResolutionHours = 4,
                            IsActive = true,
                            Name = "Kritičan",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Lookups.FaultStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsClosedState")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed_state");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_fault_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_fault_statuses_name");

                    b.ToTable("fault_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsClosedState = false,
                            Name = "Zaprimljeno",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsClosedState = false,
                            Name = "Pregledano",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IsClosedState = false,
                            Name = "Dodijeljeno",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            IsClosedState = false,
                            Name = "U radu",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            IsClosedState = false,
                            Name = "Riješeno",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            IsClosedState = true,
                            Name = "Zatvoreno",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Lookups.FaultType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_fault_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_fault_types_name");

                    b.ToTable("fault_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Elektrika",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Voda",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Grijanje",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Mreža",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Građevinski radovi",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Ostalo",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Lookups.InterventionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_intervention_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_intervention_statuses_name");

                    b.ToTable("intervention_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Planirana",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "U tijeku",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Završena",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Neuspješna",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Lookups.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_location_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_location_types_name");

                    b.ToTable("location_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Upravna zgrada",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Škola",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Zdravstvena ustanova",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Skladište",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Lookups.MaterialUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("abbreviation");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_material_units");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_material_units_name");

                    b.ToTable("material_units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "kom",
                            IsActive = true,
                            Name = "Komad",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "m",
                            IsActive = true,
                            Name = "Metar",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "l",
                            IsActive = true,
                            Name = "Litra",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "kg",
                            IsActive = true,
                            Name = "Kilogram",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "pak",
                            IsActive = true,
                            Name = "Paket",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Lookups.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_code");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Admin",
                            Description = "Pun pristup svim podacima i postavkama",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Manager",
                            Description = "Pregled svih prijava, kategorizacija, dodjela i zatvaranje",
                            Name = "Upravitelj"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Technician",
                            Description = "Rad na vlastitim nalozima i intervencijama",
                            Name = "Izvršitelj"
                        },
                        new
                        {
                            Id = 4,
                            Code = "Reporter",
                            Description = "Prijava kvarova i pregled vlastitih prijava",
                            Name = "Prijavitelj"
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MaterialUnitId")
                        .HasColumnType("integer")
                        .HasColumnName("material_unit_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_materials_code");

                    b.HasIndex("MaterialUnitId")
                        .HasDatabaseName("ix_materials_material_unit_id");

                    b.ToTable("materials", null, t =>
                        {
                            t.HasCheckConstraint("ck_materials_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<int?>("HomeLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("home_location_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Specialization")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialization");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("HomeLocationId")
                        .HasDatabaseName("ix_users_home_location_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.WorkAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("FaultReportId")
                        .HasColumnType("integer")
                        .HasColumnName("fault_report_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<string>("ReassignReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reassign_reason");

                    b.Property<int>("TechnicianUserId")
                        .HasColumnType("integer")
                        .HasColumnName("technician_user_id");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unassigned_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_work_assignments");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("ix_work_assignments_assigned_by_user_id");

                    b.HasIndex("FaultReportId")
                        .IsUnique()
                        .HasDatabaseName("ux_work_assignments_active_per_report")
                        .HasFilter("is_active AND NOT is_deleted");

                    b.HasIndex("TechnicianUserId", "IsActive")
                        .HasDatabaseName("ix_work_assignments_technician");

                    b.ToTable("work_assignments", null, t =>
                        {
                            t.HasCheckConstraint("ck_work_assignments_unassigned", "is_active = false OR unassigned_at IS NULL");
                        });
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Attachment", b =>
                {
                    b.HasOne("EKvarovi.Api.Entities.FaultReport", "FaultReport")
                        .WithMany()
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attachments_fault_reports_fault_report_id");

                    b.HasOne("EKvarovi.Api.Entities.Intervention", "Intervention")
                        .WithMany()
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attachments_interventions_intervention_id");

                    b.HasOne("EKvarovi.Api.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_users_uploaded_by_user_id");

                    b.Navigation("FaultReport");

                    b.Navigation("Intervention");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.FaultReport", b =>
                {
                    b.HasOne("EKvarovi.Api.Entities.User", "ClosedByUser")
                        .WithMany()
                        .HasForeignKey("ClosedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fault_reports_users_closed_by_user_id");

                    b.HasOne("EKvarovi.Api.Entities.Lookups.FaultPriority", "FaultPriority")
                        .WithMany()
                        .HasForeignKey("FaultPriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fault_reports_fault_priorities_fault_priority_id");

                    b.HasOne("EKvarovi.Api.Entities.Lookups.FaultStatus", "FaultStatus")
                        .WithMany()
                        .HasForeignKey("FaultStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fault_reports_fault_statuses_fault_status_id");

                    b.HasOne("EKvarovi.Api.Entities.Lookups.FaultType", "FaultType")
                        .WithMany()
                        .HasForeignKey("FaultTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fault_reports_fault_types_fault_type_id");

                    b.HasOne("EKvarovi.Api.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fault_reports_locations_location_id");

                    b.HasOne("EKvarovi.Api.Entities.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fault_reports_users_reported_by_user_id");

                    b.HasOne("EKvarovi.Api.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fault_reports_users_reviewed_by_user_id");

                    b.Navigation("ClosedByUser");

                    b.Navigation("FaultPriority");

                    b.Navigation("FaultStatus");

                    b.Navigation("FaultType");

                    b.Navigation("Location");

                    b.Navigation("ReportedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.FaultReportHistory", b =>
                {
                    b.HasOne("EKvarovi.Api.Entities.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fault_report_histories_users_changed_by_user_id");

                    b.HasOne("EKvarovi.Api.Entities.FaultReport", "FaultReport")
                        .WithMany()
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fault_report_histories_fault_reports_fault_report_id");

                    b.Navigation("ChangedByUser");

                    b.Navigation("FaultReport");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Intervention", b =>
                {
                    b.HasOne("EKvarovi.Api.Entities.FaultReport", "FaultReport")
                        .WithMany("Interventions")
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interventions_fault_reports_fault_report_id");

                    b.HasOne("EKvarovi.Api.Entities.Lookups.InterventionStatus", "InterventionStatus")
                        .WithMany()
                        .HasForeignKey("InterventionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interventions_intervention_statuses_intervention_status_id");

                    b.HasOne("EKvarovi.Api.Entities.User", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interventions_users_technician_user_id");

                    b.HasOne("EKvarovi.Api.Entities.WorkAssignment", "WorkAssignment")
                        .WithMany("Interventions")
                        .HasForeignKey("WorkAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interventions_work_assignments_work_assignment_id");

                    b.Navigation("FaultReport");

                    b.Navigation("InterventionStatus");

                    b.Navigation("Technician");

                    b.Navigation("WorkAssignment");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.InterventionMaterial", b =>
                {
                    b.HasOne("EKvarovi.Api.Entities.Intervention", "Intervention")
                        .WithMany()
                        .HasForeignKey("InterventionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_materials_interventions_intervention_id");

                    b.HasOne("EKvarovi.Api.Entities.Material", "Material")
                        .WithMany("InterventionMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_intervention_materials_materials_material_id");

                    b.Navigation("Intervention");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Location", b =>
                {
                    b.HasOne("EKvarovi.Api.Entities.Lookups.LocationType", "LocationType")
                        .WithMany()
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_locations_location_types_location_type_id");

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Material", b =>
                {
                    b.HasOne("EKvarovi.Api.Entities.Lookups.MaterialUnit", "MaterialUnit")
                        .WithMany()
                        .HasForeignKey("MaterialUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_materials_material_units_material_unit_id");

                    b.Navigation("MaterialUnit");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.User", b =>
                {
                    b.HasOne("EKvarovi.Api.Entities.Location", "HomeLocation")
                        .WithMany("HomeUsers")
                        .HasForeignKey("HomeLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_locations_home_location_id");

                    b.Navigation("HomeLocation");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.UserRole", b =>
                {
                    b.HasOne("EKvarovi.Api.Entities.Lookups.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("EKvarovi.Api.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.WorkAssignment", b =>
                {
                    b.HasOne("EKvarovi.Api.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_assignments_users_assigned_by_user_id");

                    b.HasOne("EKvarovi.Api.Entities.FaultReport", "FaultReport")
                        .WithMany("WorkAssignments")
                        .HasForeignKey("FaultReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_assignments_fault_reports_fault_report_id");

                    b.HasOne("EKvarovi.Api.Entities.User", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_assignments_users_technician_user_id");

                    b.Navigation("AssignedByUser");

                    b.Navigation("FaultReport");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.FaultReport", b =>
                {
                    b.Navigation("Interventions");

                    b.Navigation("WorkAssignments");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Location", b =>
                {
                    b.Navigation("HomeUsers");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.Material", b =>
                {
                    b.Navigation("InterventionMaterials");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EKvarovi.Api.Entities.WorkAssignment", b =>
                {
                    b.Navigation("Interventions");
                });
#pragma warning restore 612, 618
        }
    }
}
